services:
  web:
    image: wordpress:latest
    container_name: wp-ola-grande-web
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: surfero
      WORDPRESS_DB_PASSWORD: ola123
      WORDPRESS_DB_NAME: ola_db
    volumes:
      # EL TRUCO ESTÁ AQUÍ: Conectamos tu repo directamente a la carpeta de temas de WP
      - ../examen_ola_grande:/var/www/html/wp-content/themes/ola-grande-wordpress
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: wp-ola-grande-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ola_db
      MYSQL_USER: surfero
      MYSQL_PASSWORD: ola123
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp-ola-pma
